// <auto-generated />
//
// Generated by https://app.quicktype.io
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using DEM.Net.Core.EarthData;
//
//    var nasaCmrGranuleResult = NasaCmrGranuleResult.FromJson(jsonString);

namespace DEM.Net.Core.EarthData
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class NasaCmrGranuleResult
    {
        [JsonProperty("feed")]
        public Feed Feed { get; set; }
    }

    public partial class Feed
    {
        [JsonProperty("updated")]
        public DateTimeOffset Updated { get; set; }

        [JsonProperty("id")]
        public Uri Id { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("entry")]
        public List<Entry> Entry { get; set; }
    }

    public partial class Entry
    {
        [JsonProperty("producer_granule_id")]
        public string ProducerGranuleId { get; set; }

        [JsonProperty("boxes")]
        public List<string> Boxes { get; set; }

        [JsonProperty("time_start")]
        public DateTimeOffset TimeStart { get; set; }

        [JsonProperty("updated")]
        public DateTimeOffset Updated { get; set; }

        [JsonProperty("dataset_id")]
        public DatasetId DatasetId { get; set; }

        [JsonProperty("data_center")]
        public DataCenter DataCenter { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("coordinate_system")]
        public CoordinateSystem CoordinateSystem { get; set; }

        [JsonProperty("day_night_flag")]
        public DayNightFlag DayNightFlag { get; set; }

        [JsonProperty("time_end")]
        public DateTimeOffset TimeEnd { get; set; }

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("original_format")]
        public OriginalFormat OriginalFormat { get; set; }

        [JsonProperty("granule_size")]
        public string GranuleSize { get; set; }

        [JsonProperty("browse_flag")]
        public bool BrowseFlag { get; set; }

        [JsonProperty("collection_concept_id")]
        public CollectionConceptId CollectionConceptId { get; set; }

        [JsonProperty("online_access_flag")]
        public bool OnlineAccessFlag { get; set; }

        [JsonProperty("links")]
        public List<Link> Links { get; set; }
    }

    public partial class Link
    {
        [JsonProperty("rel")]
        public Uri Rel { get; set; }

        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public TypeEnum? Type { get; set; }

        [JsonProperty("title", NullValueHandling = NullValueHandling.Ignore)]
        public string Title { get; set; }

        [JsonProperty("hreflang")]
        public Hreflang Hreflang { get; set; }

        [JsonProperty("href")]
        public Uri Href { get; set; }

        [JsonProperty("inherited", NullValueHandling = NullValueHandling.Ignore)]
        public bool? Inherited { get; set; }
    }

    public enum CollectionConceptId { C1575726572LpdaacEcs };

    public enum CoordinateSystem { Geodetic };

    public enum DataCenter { LpdaacEcs };

    public enum DatasetId { AsterGlobalDigitalElevationModelV003 };

    public enum DayNightFlag { Unspecified };

    public enum Hreflang { EnUs };

    public enum TypeEnum { ApplicationZip, ImageJpeg, TextHtml, TextXml };

    public enum OriginalFormat { Echo10 };

    public partial class NasaCmrGranuleResult
    {
        public static NasaCmrGranuleResult FromJson(string json) => JsonConvert.DeserializeObject<NasaCmrGranuleResult>(json, DEM.Net.Core.EarthData.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this NasaCmrGranuleResult self) => JsonConvert.SerializeObject(self, DEM.Net.Core.EarthData.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                CollectionConceptIdConverter.Singleton,
                CoordinateSystemConverter.Singleton,
                DataCenterConverter.Singleton,
                DatasetIdConverter.Singleton,
                DayNightFlagConverter.Singleton,
                HreflangConverter.Singleton,
                TypeEnumConverter.Singleton,
                OriginalFormatConverter.Singleton,
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }

    internal class CollectionConceptIdConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(CollectionConceptId) || t == typeof(CollectionConceptId?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "C1575726572-LPDAAC_ECS")
            {
                return CollectionConceptId.C1575726572LpdaacEcs;
            }
            throw new Exception("Cannot unmarshal type CollectionConceptId");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (CollectionConceptId)untypedValue;
            if (value == CollectionConceptId.C1575726572LpdaacEcs)
            {
                serializer.Serialize(writer, "C1575726572-LPDAAC_ECS");
                return;
            }
            throw new Exception("Cannot marshal type CollectionConceptId");
        }

        public static readonly CollectionConceptIdConverter Singleton = new CollectionConceptIdConverter();
    }

    internal class CoordinateSystemConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(CoordinateSystem) || t == typeof(CoordinateSystem?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "GEODETIC")
            {
                return CoordinateSystem.Geodetic;
            }
            throw new Exception("Cannot unmarshal type CoordinateSystem");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (CoordinateSystem)untypedValue;
            if (value == CoordinateSystem.Geodetic)
            {
                serializer.Serialize(writer, "GEODETIC");
                return;
            }
            throw new Exception("Cannot marshal type CoordinateSystem");
        }

        public static readonly CoordinateSystemConverter Singleton = new CoordinateSystemConverter();
    }

    internal class DataCenterConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(DataCenter) || t == typeof(DataCenter?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "LPDAAC_ECS")
            {
                return DataCenter.LpdaacEcs;
            }
            throw new Exception("Cannot unmarshal type DataCenter");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (DataCenter)untypedValue;
            if (value == DataCenter.LpdaacEcs)
            {
                serializer.Serialize(writer, "LPDAAC_ECS");
                return;
            }
            throw new Exception("Cannot marshal type DataCenter");
        }

        public static readonly DataCenterConverter Singleton = new DataCenterConverter();
    }

    internal class DatasetIdConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(DatasetId) || t == typeof(DatasetId?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "ASTER Global Digital Elevation Model V003")
            {
                return DatasetId.AsterGlobalDigitalElevationModelV003;
            }
            throw new Exception("Cannot unmarshal type DatasetId");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (DatasetId)untypedValue;
            if (value == DatasetId.AsterGlobalDigitalElevationModelV003)
            {
                serializer.Serialize(writer, "ASTER Global Digital Elevation Model V003");
                return;
            }
            throw new Exception("Cannot marshal type DatasetId");
        }

        public static readonly DatasetIdConverter Singleton = new DatasetIdConverter();
    }

    internal class DayNightFlagConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(DayNightFlag) || t == typeof(DayNightFlag?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "UNSPECIFIED")
            {
                return DayNightFlag.Unspecified;
            }
            throw new Exception("Cannot unmarshal type DayNightFlag");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (DayNightFlag)untypedValue;
            if (value == DayNightFlag.Unspecified)
            {
                serializer.Serialize(writer, "UNSPECIFIED");
                return;
            }
            throw new Exception("Cannot marshal type DayNightFlag");
        }

        public static readonly DayNightFlagConverter Singleton = new DayNightFlagConverter();
    }

    internal class HreflangConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(Hreflang) || t == typeof(Hreflang?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "en-US")
            {
                return Hreflang.EnUs;
            }
            throw new Exception("Cannot unmarshal type Hreflang");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (Hreflang)untypedValue;
            if (value == Hreflang.EnUs)
            {
                serializer.Serialize(writer, "en-US");
                return;
            }
            throw new Exception("Cannot marshal type Hreflang");
        }

        public static readonly HreflangConverter Singleton = new HreflangConverter();
    }

    internal class TypeEnumConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(TypeEnum) || t == typeof(TypeEnum?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            switch (value)
            {
                case "application/zip":
                    return TypeEnum.ApplicationZip;
                case "image/jpeg":
                    return TypeEnum.ImageJpeg;
                case "text/html":
                    return TypeEnum.TextHtml;
                case "text/xml":
                    return TypeEnum.TextXml;
            }
            throw new Exception("Cannot unmarshal type TypeEnum");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (TypeEnum)untypedValue;
            switch (value)
            {
                case TypeEnum.ApplicationZip:
                    serializer.Serialize(writer, "application/zip");
                    return;
                case TypeEnum.ImageJpeg:
                    serializer.Serialize(writer, "image/jpeg");
                    return;
                case TypeEnum.TextHtml:
                    serializer.Serialize(writer, "text/html");
                    return;
                case TypeEnum.TextXml:
                    serializer.Serialize(writer, "text/xml");
                    return;
            }
            throw new Exception("Cannot marshal type TypeEnum");
        }

        public static readonly TypeEnumConverter Singleton = new TypeEnumConverter();
    }

    internal class OriginalFormatConverter : JsonConverter
    {
        public override bool CanConvert(Type t) => t == typeof(OriginalFormat) || t == typeof(OriginalFormat?);

        public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
        {
            if (reader.TokenType == JsonToken.Null) return null;
            var value = serializer.Deserialize<string>(reader);
            if (value == "ECHO10")
            {
                return OriginalFormat.Echo10;
            }
            throw new Exception("Cannot unmarshal type OriginalFormat");
        }

        public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
        {
            if (untypedValue == null)
            {
                serializer.Serialize(writer, null);
                return;
            }
            var value = (OriginalFormat)untypedValue;
            if (value == OriginalFormat.Echo10)
            {
                serializer.Serialize(writer, "ECHO10");
                return;
            }
            throw new Exception("Cannot marshal type OriginalFormat");
        }

        public static readonly OriginalFormatConverter Singleton = new OriginalFormatConverter();
    }
}
